# Generated by Django 5.2.8 on 2025-12-14 10:19

from django.db import migrations


DEFAULT_ROLES = [
    {
        "code": "student",
        "name": "Student",
        "description": "Default student role",
        "is_active": True,
    },
]


def create_roles(apps, _):
    Role = apps.get_model('accounts', 'Role')    
    for role in DEFAULT_ROLES:
        defaults = role.copy()
        code = defaults.pop("code")
        Role.objects.get_or_create(code=code, defaults=defaults)


def remove_roles(apps, _):
    Role = apps.get_model('accounts', 'Role')
    codes = [role["code"] for role in DEFAULT_ROLES]
    Role.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, remove_roles),
    ]
