stages:
  - build
  - test

.mount-secrets:
  script:
    - install -D db/db_app_passwd.txt /run/secrets/db_app_passwd

build-frontend:
  stage: build
  image: node:22-alpine3.21
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm run build

test-backend:
  stage: test
  image: python:3.12-slim
  script:
    - !reference [.mount-secrets, script]
    - cd backend
    - pip install -r requirements-dev.txt
    - python3 -m flake8 manage.py config/ ping/
    - pip install -r requirements.txt
    - python3 manage.py check
    - python3 manage.py test
