services:
  db:
    build: ./db
    image: pzsp2-db
    env_file: "db/db.env"
    ports:
      - "27017:27017"
    networks:
      - back-tier
    command:
      - "--config"
      - "/etc/mongo/mongod.conf"
    tmpfs:
      - "/data/db"
    secrets:
      - db_passwd
      - db_app_passwd
  
  backend:
    build: ./backend
    image: pzsp2-backend
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret"
      CORS_ALLOWED_ORIGINS: "https://localhost"
    ports:
      - "8000:8000"
    networks:
      - back-tier
      - front-tier
    restart: unless-stopped
    secrets:
      - db_app_passwd
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: pzsp2-frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-tier
    depends_on:
      backend:
        condition: service_healthy

networks:
  back-tier:
  front-tier:

secrets:
  db_passwd:
    file: db/db_passwd.txt
  db_app_passwd:
    file: db/db_app_passwd.txt
