version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pzsp2-db
    restart: unless-stopped
    networks:
      - back-tier
    environment:
      POSTGRES_DB: szkola
      POSTGRES_USER: app
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d szkola"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    image: pzsp2-backend
    restart: unless-stopped
    networks:
      - back-tier
      - front-tier
    environment:
      DJANGO_DEBUG: "0"
      DJANGO_SECRET_KEY: "change-me"
      DJANGO_ALLOWED_HOSTS: "backend,localhost,127.0.0.1"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
      POSTGRES_DB: szkola
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "RybyZjedza"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    image: pzsp2-frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front-tier
    depends_on:
      backend:
        condition: service_healthy

networks:
  back-tier:
  front-tier:

volumes:
  db-data:
