# Generated by Django 5.2.8 on 2026-01-04 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('school', '0004_alter_instructor_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentallocation',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-period_start', '-created_at']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('void', 'Void')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('card', 'Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('student', 'period_start'), name='uniq_purchase_student_month'),
        ),
        migrations.DeleteModel(
            name='PaymentAllocation',
        ),
    ]
