# Generated by Django 5.2.8 on 2026-01-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_paymentallocation_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passproduct',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='passproduct',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='passproduct',
            name='validity_months',
        ),
    ]
