# Generated by Django 5.2.9 on 2026-01-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_passproduct_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passproduct',
            options={'ordering': ['-is_active', 'created_at', 'name']},
        ),
    ]
