# Generated by Django 5.2.8 on 2026-01-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_paymentallocation_purchase_and_more'),
        ('school', '0004_alter_instructor_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.passproduct'),
        ),
    ]
