# Generated by Django 5.2.8 on 2026-01-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_passproduct_options'),
        ('school', '0005_student_pass_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pass_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='billing.passproduct'),
        ),
    ]
